name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Install dependecies
          run: nmp install

        - name: Build application
          run: npm run build:all

        - name: Deploy to Github Pages
          uses: JamesIves/github-pages-deploy-action@v4
          with: 
            folder: build
